
model:
  class_path: lcap.methods.style.StyleTransferSystem
  init_args:
    lr: 0.0001
    max_epochs: 500
    weight_decay: 0.0001
    vst_json: scripts/data/vst-chains/eq+multiband-comp+limiter.json
    loss_type: audio
    grad_type: autodiff
    autodiff_processor: simple
    on_the_fly: True
    split_section: True

    encoder:
      class_path: lcap.models.panns.Cnn14
      init_args:
        embed_dim: 512
        sample_rate: 48000
        window_size: 2048
        hop_size: 1024
        mel_bins: 128
        fmin: 20
        fmax: 20000
        use_batchnorm: True
        input_norm: minmax
