model:
  class_path: lcap.methods.param.ParameterEstimator
  init_args:
    lr: 0.0001
    num_instances: 63
    num_presets: 10
    max_epochs: 250
    weight_decay: 0.0001
    embed_mode: diff
    norm: L2
    
    encoder:
      class_path: lcap.models.panns.Cnn14
      init_args:
        embed_dim: 512
        sample_rate: 48000
        window_size: 2048
        hop_size: 1024
        mel_bins: 128
        fmin: 20
        fmax: 20000
        use_batchnorm: True
        input_norm: minmax
