# pretrained and frozen CLAP model
model:
  class_path: lcap.methods.param.ParameterEstimator
  init_args:
    lr: 0.0001
    num_instances: 63
    num_presets: 10
    max_epochs: 100
    weight_decay: 0.0001
    
    encoder:
      class_path: lcap.models.clap.CLAP
      init_args:
        pretrained: true
        frozen: true
